### ISSUE TITLE
[WCJS] Uncaught error in IE11: SCRIPT5045 Assignment to read-only properties is not allowed in strict mode`

### ISSUE THREAD

**Issue by LarsVonQualen** [webcomponents/polyfills#115]
Hi,
so I have to support IE11, i know, not ideal.

When i include the webcomponents-bundle.js file, IE will throw this error
`SCRIPT5045: Assignment to read-only properties is not allowed in strict mode`
here:
[https://github.com/webcomponents/custom-elements/blob/master/src/CustomElementRegistry.js#L267](https://github.com/webcomponents/custom-elements/blob/master/src/CustomElementRegistry.js#L267)

I'm not sure exactly why, or if this is even an issue, everything seems to actually work, it's just an annoyance, and i guess there's the risk of IE showing an unexpected error popup to the user.

It seems to me that the error should be handled gracefully thus not ending in console output.

Any thoughts? Or maybe even a way to get the error to go away? 😄

**Comment by Sijmen** [comment]
I've ran into the same issue while developing a custom component with Angular. In the angular docs it says: 

> In browsers that support Custom Elements natively, the specification requires developers use ES2015 classes to define Custom Elements - developers can opt-in to this by setting the target: "es2015" property in their project's tsconfig.json. As Custom Element and ES2015 support may not be available in all browsers, developers can instead choose to use a polyfill to support older browsers and ES5 code.

So I changed the target from 'es2015' to 'ES5' and the read-only strict error disappeared.  For me it was a blocking issue, as it crashed the script and the elements were never loaded.

**Comment by sguft** [comment]
We ran into this problem as well and the problem seems to be that we have a combination of "use strict" as well as assignment to window.CustomElementRegistry which causes this error in IE11.

This is easily reproducable by trying out the following in the console in IE11:

`(function() {
    'use strict';
    window.CustomElementRegistry = '';
}());`

We fixed it on our side by removing "use strict" from custom-elements.min.js, but I don't expect this to be the official way to fix it - however it allowed us to continue until the library has been fixed. I hope my additional info here will help that process.

**Comment by icyerasor** [comment]
> This is easily reproducable by trying out the following in the console in IE11:
> 
> `(function() { 'use strict'; window.CustomElementRegistry = ''; }());`
> 
> We fixed it on our side by removing "use strict" from custom-elements.min.js, but I don't expect this to be the official way to fix it - however it allowed us to continue until the library has been fixed. I hope my additional info here will help that process.

can still confirm this behavior / fix.
Any update on when this could be fixed to avoid having to use local modifications?

**Comment by wbern** [comment]
I can confirm that the fix @sguft mentioned by removing "use strict" fixed it.. We searched all our code for typescript projects that target ES2015 as @Sijmen mentioned but all were targeting es5.

The offending file for us was indeed a .ts file however.

**Comment by SmallhillCZ** [comment]
I tried updating to Angular 11, but the error is still there, so can't confirm @icyerasor's update from https://github.com/webcomponents/polyfills/issues/115#issuecomment-611644891

I can confirm the error is something around `window.CustomElementRegistry=$`

**Comment by amelnikoff** [comment]
In my case with Angular 10 I had this line first
`import 'document-register-element';`
before 
`import '@webcomponents/custom-elements';`

'document-register-element' enabled strict mode. Putting it after 'webcomponents' solves error.
